### ISSUE TITLE
Callback behavior buggy

### ISSUE THREAD

**Issue by joaorolemberg** [khoih-prog/AsyncHTTPSRequest_Generic#19]
I will not send much information because i believe that is equal to a problem in http library and was solved (https://github.com/khoih-prog/AsyncHTTPRequest_Generic/issues/43 ). I have expecienced the same behavior of this solved issue on my esp32.

**Comment by khoih-prog** [comment]
Hi @joaorolemberg 

The new [**AsyncHTTPSRequest_Generic** v2.5.0](https://github.com/khoih-prog/AsyncHTTPSRequest_Generic/releases/tag/v2.5.0) has just been published. Your contribution is noted in [**Contributions and Thanks**](https://github.com/khoih-prog/AsyncHTTPSRequest_Generic#contributions-and-thanks)

Please test and report more bugs.

Best Regards,

---

### Releases v2.5.0

1. Add support to ESP32 boards using `LwIP W6100 Ethernet`
2. Fix bug of wrong `reqStates`. Check [Callback behavior buggy #19](https://github.com/khoih-prog/AsyncHTTPSRequest_Generic/issues/19)
3. Fix bug of `_parseURL()`. Check [Bug with _parseURL() #21](https://github.com/khoih-prog/AsyncHTTPSRequest_Generic/issues/21)
4. Improve `README.md` so that links can be used in other sites, such as `PIO`
