### ISSUE TITLE
Conflict with ESP32-HUB75-MatrixPanel-I2S-DMA

### ISSUE THREAD

**Issue by m-maazi** [khoih-prog/AsyncHTTPSRequest_Generic#6]
I found a problem when using the this library and ESP32-HUB75-MatrixPanel-I2S-DMA. If I activate that library, responses to requests from AsyncHTTPSRequest_Generic come significantly later than without it.
Is there any workaround?

[](https://github.com/mrfaptastic/ESP32-HUB75-MatrixPanel-I2S-DMA)

**Comment by khoih-prog** [comment]
Thanks for your interest in this library.

Sorry that you have to figure out the issue by **yourself** because you add that `ESP32-HUB75-MatrixPanel-I2S-DMA` library, which interferes somehow with the basic operation of this library. 

I have no idea what that library is doing and **won't spend time** to figure out. You can also post an issue on that `ESP32-HUB75-MatrixPanel-I2S-DMA` library.

There is no way for any library, even the ESP32 core, to survive, if you just add more and more libraries without knowing the basic operations of each library.

Good Luck,
